add new SLACK_WEBHOOK_URL

diff --git a/.github/workflows/retirejs-scan.yml b/.github/workflows/retirejs-scan.yml
--- a/.github/workflows/retirejs-scan.yml
+++ b/.github/workflows/retirejs-scan.yml
@@ -113,13 +113,18 @@ jobs:
     - name: Run RetireJS Scan
       run: retire --outputformat json --outputpath retirejs-report.json --verbose --exitwith 0
 
-    - name: Check for Medium Vulnerabilities
+    # check the JSON if it vulnerable medium or high
+    - name: Check RetireJS Report for Medium and High Vulnerabilities
       run: |
-        if true; then 
-        curl -X POST -H 'Content-type: application/json' --data \
-          '{"text":":rotating_light: *Medium vulnerability detected in RetireJS report!* \n*Committer:* ${{ github.actor }} \n*Repository:* ${{ github.repository }} \n"}' \
-          ${{ secrets.SLACK_WEBHOOK_URL }};
-      
+        if grep -q '"severity": "medium"' retirejs-report.json; then
+          echo "::error::Medium vulnerability detected by RetireJS!";
+          exit 1;
+        elif grep -q '"severity": "high"' retirejs-report.json; then
+          echo "::error::High vulnerability detected by RetireJS!";
+          exit 1;
+        else
+          echo "No medium or high vulnerabilities found in RetireJS report.";
+        fi
 
     - name: Upload RetireJS Report
       uses: actions/upload-artifact@v4
